// https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab
class Solution{
    public:
    // arr: input array
    // n: size of array
    //Function to find the sum of contiguous subarray with maximum sum.
    long long maxSubarraySum(int a[], int n){
        
        // Your code here
       long long sum=0,maxi=INT_MIN;
       for(int i=0;i<n;i++)
       {
           sum=sum+a[i];
           maxi=max(maxi,sum);
           sum<0?sum=0:sum=sum;
       }
       return maxi;
    }
};
